services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=!root123Qwe123
      - MSSQL_PID=Developer
    volumes:
      - sqlserverdata:/var/opt/mssql
    networks:
      - webapp-network

  redis:
    image: redis:7.4-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    command: redis-server --requirepass your_password --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - webapp-network

volumes:
  sqlserverdata:
  redis_data:
 
networks:
  webapp-network:
    driver: bridge  
  