<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <!-- Disable default globbing so Web project does not compile other projects' source files
       which are located under the same 'src' directory. Explicitly include only Web-specific
       source files here (Program.cs). -->
  <PropertyGroup>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Middleware\GlobalExceptionHandler.cs" />
    <Compile Include="Middleware\RateLimiterMiddleware.cs" />
    <Compile Include="Program.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
	<PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
	<PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
	<PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
	<PackageReference Include="Serilog.Settings.Configuration" Version="10.0.0" />
	<PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
	<PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Application\Application.csproj" />
    <ProjectReference Include="..\Core\Domain\Domain.csproj" />
    <ProjectReference Include="..\Core\Infrastructure\Infrastructure.csproj" />
    <ProjectReference Include="..\Core\Presentation\Presentation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="appsettings.Example.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="appsettings.Production.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
