<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <!-- Disable default globbing so Web project does not compile other projects' source files
       which are located under the same 'src' directory. Explicitly include only Web-specific
       source files here (Program.cs). -->
  <PropertyGroup>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Middleware\GlobalExceptionHandler.cs" />
    <Compile Include="Program.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Application\Application.csproj" />
    <ProjectReference Include="..\Core\Domain\Domain.csproj" />
    <ProjectReference Include="..\Core\Infrastructure\Infrastructure.csproj" />
    <ProjectReference Include="..\Core\Presentation\Presentation.csproj" />
  </ItemGroup>

</Project>
